### ISSUE TITLE
Server does not bind to all network interfaces

### ISSUE THREAD

**Issue by chazzbg** [varun-raj/immich-power-tools#106]
I have a setup where with docker compose i setup immich power tools to be part of two networks. one is the immich network, other one is the traefik network for the reverse proxying.

Here is a sample compose.yml 

```yaml
services:
  power-tools:
    container_name: immich-power-tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    restart: unless-stopped
    environment:
      IMMICH_API_KEY: # your_immich_api_key
      IMMICH_URL: "http://immich-server:2283" # Your immich instace ip address and port
      EXTERNAL_IMMICH_URL: "https://immich.external" # External address of immich
    networks:
      - traefik
      - immich
networks:
  immich:
    name: immich
  traefik:
    external: true
    
```

But when starting, immich power tools server does not bind to all the network interfaces 

here is the log of the container of power tools

```
2025-01-02T09:12:40.952257000Z   ▲ Next.js 14.2.5

2025-01-02T09:12:40.952408000Z   - Local:        http://48d63b3c3973:3000

2025-01-02T09:12:40.952457000Z   - Network:      http://172.26.0.5:3000

2025-01-02T09:12:40.952524000Z 

2025-01-02T09:12:40.952575000Z  ✓ Starting...

2025-01-02T09:12:41.171530000Z  ✓ Ready in 228ms
```

Is there a way to specify to which ip the server will bind? or a fix in the code is needed ?
