### ISSUE TITLE
Database env are not seen

### ISSUE THREAD

**Issue by pippo73** [varun-raj/immich-power-tools#117]
Hello, I've installed the last version present today 19/01 (I think the 0.13) but it seems it cannot read the .env infos

![Image](https://github.com/user-attachments/assets/bfaf56d1-ce45-456f-bc94-e76faada9d00)

```

$ docker logs immich_power_tools -f

 ✓ Starting...
 ✓ Ready in 211ms
  ▲ Next.js 14.2.5
  - Local:        http://4223b2dc460f:3000
  - Network:      http://172.18.0.3:3000

```

Anyway to debug the problem somehow?

Here are the configuration I've extracted from the compose.yaml file

```
  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - "8001:3000"
    env_file:
      - .env
```

and in the .env file

```

###########
# powerTools
###########

IMMICH_API_KEY=xxxxx
IMMICH_URL = "http://192.168.1.xxx:2283"
EXTERNAL_IMMICH_URL = "https://xxx.xxx.xxx"

```
