### ISSUE TITLE
Suggestion Healtcheck

### ISSUE THREAD

**Issue by stanthewizzard** [varun-raj/immich-power-tools#121]
Hello

Could it be possible to have an healtcheck inside the docker ?
for autoheal purposes

Thanks

**Comment by varun-raj** [comment]
You can use the below for the health check

```
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

```
