### ISSUE TITLE
Need Help Install Power-Tools

### ISSUE THREAD

**Issue by kaylopez1962** [varun-raj/immich-power-tools#124]
I have attempted to install Power-Tools and I am getting the following message:  

Database connection failed
getaddrinfo ENOTFOUND "immich-postgres"

How do I find the correct value to enter into the .env file?  I have tried "datebase", the IP address of my Immich install.  No luck.  Please help.

Thank you so much!

**Comment by iolaire** [comment]
Look at your docker compose in the settings for the database, does it have a container_name?  If so use that.  For example in this sample of my docker compose I have  "container_name: immich_postgres"

```
name: immich

services:
.. other items removed ..
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
```

**Comment by NightHawkATL** [comment]
I am running into the same issue: 
![Image](https://github.com/user-attachments/assets/c042d399-f506-46f8-90d2-8fc4e0a45cb4)

This is the only thing showing in the logs:
![Image](https://github.com/user-attachments/assets/482c9b9d-50a5-447a-87a1-363ff9502f96)

Here is the compose for postgres:
![Image](https://github.com/user-attachments/assets/5ef1fcf3-fc17-4718-aa76-fe6990511bb1)

Here is the power tools compose:
![Image](https://github.com/user-attachments/assets/6a16a509-912c-4581-9672-eb1c876d813a)

**Comment by kaylopez1962** [comment]
> Look at your docker compose in the settings for the database, does it have a container_name? If so use that. For example in this sample of my docker compose I have "container_name: immich_postgres"
> 
> ```
> name: immich
> 
> services:
> .. other items removed ..
>   database:
>     container_name: immich_postgres
>     image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
>     environment:
>       POSTGRES_PASSWORD: ${DB_PASSWORD}
>       POSTGRES_USER: ${DB_USERNAME}
>       POSTGRES_DB: ${DB_DATABASE_NAME}
>       POSTGRES_INITDB_ARGS: '--data-checksums'
>     volumes:
>       # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
>       - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
> ```



> Look at your docker compose in the settings for the database, does it have a container_name? If so use that. For example in this sample of my docker compose I have "container_name: immich_postgres"
> 
> ```
> name: immich
> 
> services:
> .. other items removed ..
>   database:
>     container_name: immich_postgres
>     image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
>     environment:
>       POSTGRES_PASSWORD: ${DB_PASSWORD}
>       POSTGRES_USER: ${DB_USERNAME}
>       POSTGRES_DB: ${DB_DATABASE_NAME}
>       POSTGRES_INITDB_ARGS: '--data-checksums'
>     volumes:
>       # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
>       - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
> ```

I have tried this and I am still getting the same error message that I indicated.

**Comment by kaylopez1962** [comment]
I have tried the suggested solution and I am still getting the same error message.

**Comment by iolaire** [comment]
You are probably already doing it but have you stopped and re-loaded the docker compose for both power tools and immich?
i.e.
```
docker compose stop
docker  compose up -d
```

**Comment by NightHawkATL** [comment]
I just restarted my whole immich stack and get the same error.

**Comment by iolaire** [comment]
My only other suggestion is to read through the logs on the power tools docker instance to see if those show anything.

**Comment by NightHawkATL** [comment]
> My only other suggestion is to read through the logs on the power tools docker instance to see if those show anything.

This is all the docker logs show.
![Image](https://github.com/user-attachments/assets/e289cab5-bfce-4b1c-b4d3-a67be64d5630)

**Comment by varun-raj** [comment]
Hi, Can you check if immich db and power tools are in the same docker network?

**Comment by NightHawkATL** [comment]
I have all my Immich stuff in a single stack so they will all be on the same docker network. Simplifies communications most times..

**Comment by varun-raj** [comment]
@NightHawkATL  can you try changing the hypen in your immich url to underscore?

immich-server -> immich_server

**Comment by NightHawkATL** [comment]
Here is the latest with the updated changes.

![Image](https://github.com/user-attachments/assets/4e841b9e-85b1-4e42-9203-e5c9bb23e275)

![Image](https://github.com/user-attachments/assets/98a21c3b-1641-454f-bd6c-b9f4a5610653)

**Comment by satmandu** [comment]
I finally got this to work.

This is what I added for just power-tools in my `docker-compose.yml`:
```yaml
  # Other services...
  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    networks:
      - immich_network
    environment:
      DB_HOST: immich_postgres
      DB_PORT: 5432
      IMMICH_URL: "http://immich_server:2283"
    ports:
      - "8001:3000"
    env_file:
      - .env
 ```

I also added this at the bottom of my `docker-compose.yml`:
```yaml
networks:
  immich_network:
    driver: bridge
```

Additionally, I made sure that _**every service**_ in `docker-compose.yml` also had this:
```yaml
networks:
      - immich_network
 ```

**Comment by jamess60** [comment]
+1, getting the same issue. My config is identical to @NightHawkATL

**Comment by pchresta** [comment]
Try removing the `" "` and also remove the whitepsaces from the environment like this:

  IMMICH_URL=
  IMMICH_API_KEY= 
  DB_USERNAME=
  DB_PASSWORD=
  DB_HOST=
  DB_PORT=
  DB_DATABASE_NAME=

**Comment by naamah75** [comment]
This is my solution for installing on TrueNAS:

```
networks:
  immich-network:
    external: True
    name: ix-immich_default
services:
  immich-power-tools:
    environment:
      DB_DATABASE_NAME: immich
      DB_HOST: ix-immich-pgvecto-1
      DB_PASSWORD: ****
      DB_PORT: '5432'
      DB_USERNAME: immich
      EXTERNAL_IMMICH_URL: http://****:2283
      GEMINI_API_KEY: ****
      GOOGLE_MAPS_API_KEY: ****
      IMMICH_API_KEY: ****
      IMMICH_URL: http://****:30041
      SECURE_COOKIE: 'true'
    image: ghcr.io/varun-raj/immich-power-tools:latest
    networks:
      - immich-network
    ports:
      - '30042:3000'
    restart: unless-stopped
```
