### ISSUE TITLE
Gemini does not work

### ISSUE THREAD

**Issue by janusloo** [varun-raj/immich-power-tools#133]
Hi,

I have followed instructions online to get my Google Map API key and Gemini API key. It works for Google Map API - I can see the heatmap now. But Gemini does not work.

See screenshot:

![Image](https://github.com/user-attachments/assets/7e096212-1fa4-40d9-bc0a-b602115d9b72)

And I have a few photos from last week. I recreated the Gemini API key as well but it still does not work. I can't find anything online to resolve this issue. Can you please help to point me to the right direction what I am missing?

This is my docker compose file:
```
  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - 8001:3000
    env_file:
      - powertools.env

```

Thank you for this awesome tool!
