### ISSUE TITLE
API key, DB credentials, docker and local development

### ISSUE THREAD

**Issue by Qhilm** [varun-raj/immich-power-tools#135]
Hello,

this is more of a discussion than an issue, unfortunately the discussions section is not available.

I do not understand the setup instructions, I fear. I attempted to configure it using the [docker compose method](https://github.com/varun-raj/immich-power-tools?tab=readme-ov-file#method-1---docker-compose--recommended-), adding the below to my existing immich stack:

```yaml
  power-tools:
    container_name: immich_power_tools
    user: 1037:100
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - 2284:3000
    env_file:
      - .env
    security_opt:
      # Prevent escalation of privileges after the container is started
      - no-new-privileges:true
    cap_drop:
      # Prevent access to raw network traffic
      - NET_RAW
```

(the security options are something I tend to add to containers in general – I can remove them for testing, but I don't think it has anything to do with the issue described below)

Now I can access the powertools web interface but it complains that "Some database credentials are missing: DB_HOST, DB_PORT. Please add them to the .env file"

But this is only required for "local development" according to the setup instructions (side question: what is "local development"?), unless I am misunderstanding something?
