### ISSUE TITLE
Truenas

### ISSUE THREAD

**Issue by Professorvennie** [varun-raj/immich-power-tools#62]
Anyway to get this to work with the Truenas install of Immich?

**Comment by sai80082** [comment]
@Professorvennie Unfortunately, we don't have TrueNAS running on our servers for testing. I would recommend reaching out to the Immich community for assistance.

**Comment by AlexT59** [comment]
I managed to get it to work on TrueNAS (electric el, 24.10.0.2).
Here is the docker compose:
```yaml
networks:
  immich-network:
    external: True
    name: ix-immich_default
services:
  immich-power-tools:
    env_file:
      - conf.env
    image: ghcr.io/varun-raj/immich-power-tools:latest
    networks:
      - immich-network
    ports:
      - '30042:3000'
    restart: unless-stopped
```

And the .env file:
```env
IMMICH_URL=http://server_ip:30041
EXTERNAL_IMMICH_URL=https://external.immich.url
SECURE_COOKIE=true

DB_HOST=ix-immich-pgvecto-1
DB_PORT=5432
DB_USERNAME=immich
DB_PASSWORD=***
DB_DATABASE_NAME=immich

IMMICH_API_KEY=***
```

Some details about this config:

1. Add the immich-power-tools container into the **same Immich network**
2. To get the **DB_PASSWORD**: open shell window in the Immich server container and write `echo $DB_PASSWORD`
3. To get the **IMMICH_API_KEY**: https://immich.app/docs/features/command-line-interface#obtain-the-api-key

**Comment by chocology** [comment]
Thank you for your great post.  I have been banging my head trying to get it to work on mine but I keep getting and error.

Database connection failed
getaddrinfo ENOTFOUND Jd&2Ys7W&o

[Setup Instructions](https://github.com/varun-raj/immich-power-tools?tab=readme-ov-file#-getting-started)

**Comment by AlexT59** [comment]
> Database connection failed  
> getaddrinfo ENOTFOUND Jd&2Ys7W&o
> 
> [Setup Instructions](https://github.com/varun-raj/immich-power-tools?tab=readme-ov-file#-getting-started) Connected to (External)
> 
> https://immich.domain.com/ Connected to (Internal)
> 
> http://192.168.192.2:30041/

Sorry but I doesn't understand your problem. Could you provide more logs / details ?

**Comment by chocology** [comment]
I followed your guide precisely which was more or less in line with what I was attempting prior.  The only difference was SECURE_COOKIE=false which i corrected.

Here is my docker-compose.yaml:-
networks:
  immich-network:
    external: true
    name: ix-immich_default
  ix-immich_default:
    external: true
services:
  immich-power-tools:
    env_file:
      - conf.env
    image: ghcr.io/varun-raj/immich-power-tools:latest
    networks:
      - immich-network
    ports:
      - 30042:3000
    restart: unless-stopped


When I run the container, the logs from the terminal are as below.

immich_power_tools-immich-power-tools-1  |  ✓ Starting...
immich_power_tools-immich-power-tools-1  |  ✓ Ready in 164ms
immich_power_tools-immich-power-tools-1  |   ▲ Next.js 14.2.5
immich_power_tools-immich-power-tools-1  |   - Local:        http://f5a606d88e0a:3000
immich_power_tools-immich-power-tools-1  |   - Network:      http://172.16.2.6:3000
immich_power_tools-immich-power-tools-1  | 
immich_power_tools-immich-power-tools-1  |  ✓ Starting...
immich_power_tools-immich-power-tools-1  |  ✓ Ready in 236ms

When I open bash in the container, I get this message:-
WARN[0000] The "H" variable is not set. Defaulting to a blank string. 
OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown


Upon opening the page in a browser, I get this:

![image](https://github.com/user-attachments/assets/41a3e7d1-bdad-4304-869c-a8fa6cef1c34)

Connected to (External)
https://foto.domain.com/

Connected to (Internal)
http://192.168.1.2:30041/

**Comment by AlexT59** [comment]
As you are not using the md formatting syntax your file is difficult to read but it seems that your docker compose file is not exactly the same, especially the `networks` part.
Mine is:  
```yaml
networks:
  immich-network:
    external: True
    name: ix-immich_default
```  
Yours seems to be:
```yaml
networks:
  immich-network:
    external: True
    name: ix-immich_default
  ix-immich_default:
    external: true
```  

Just to be sure, are you running on TrueNAS 24.10.0 ?

Apart from that, I don't have any other ideas, as I don't know exactly how Immich power tools work intervaly and what this error realy means.
