### ISSUE TITLE
Manage People: ERR_BAD_RESPONSE

### ISSUE THREAD

**Issue by Saargebeat** [varun-raj/immich-power-tools#63]
Heyhey,

I just installed the power tools and did a copy paste from the appdata-backup-file of immich instance. It does not give any error in log, but on the web-ui i cant see anything. Under people it give sthe "ERR_BAD_RESPONSE"

How to continue troubleshooting this?

**Comment by anupdebnath** [comment]
Same here

```
  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - "8001:3000"
    env_file:
      - .env
```

```
IMMICH_API_KEY=keys
IMMICH_URL = "http://ip:2283" # Your immich instace ip address and port
EXTERNAL_IMMICH_URL = "https://domain" # External address of immich
```
