### ISSUE TITLE
Unable to process this request, please try again later

### ISSUE THREAD

**Issue by lusu007** [varun-raj/immich-power-tools#82]
I have the following setup:

docker-compose-power-tools.yml
```yml
name: immich

services:
  immich_power_tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    networks:
      - public
      - immich
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich-tools.rule=Host(`tools.images.redacted.cloud`)"
      - "traefik.http.routers.immich-tools.entrypoints=websecure"
      - "traefik.http.routers.immich-tools.tls.certresolver=letsencrypt"
      - "traefik.http.services.immich-tools.loadbalancer.server.port=3000"
    environment:
      - IMMICH_URL="immich_server:2283" # Immich URL
      - IMMICH_API_KEY="redacted" # Immich API Key
      - EXTERNAL_IMMICH_URL="images.redacted.cloud" # External Immich URL
      - DB_USERNAME="postgres" # Postgress Database Username
      - DB_PASSWORD="redacted" # Postgres Database Password
      - DB_HOST="immich_postgres" # Postgres Host (IP address or hostname of the database)
      - DB_PORT="5432" # Postgres Port number (Default: 5432)
      - DB_DATABASE_NAME="immich" # Name of the database
      - HOSTNAME=0.0.0.0

networks:
  public:
    external: true
    name: public
  immich:
    external: true
    name: immich
```

docker-compose-immich.yml
```yml
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      - public
      - tunnel
      - immich
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`images.redacted.cloud`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls.certresolver=letsencrypt"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      - immich
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      #test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:

networks:
  public:
    external: true
    name: public
  tunnel:
    external: true
    name: tunnel
  immich:
    external: true
    name: immich
```

Immich Power Tools is exposed via Traefik which is also running on the `public` docker network.
When I try accessing power tools I get the following error:
![image](https://github.com/user-attachments/assets/5b635b0e-bb5b-4fd5-ba13-b7d04916cd67)

I cant find any log output in the power-tools container log.
