### ISSUE TITLE
Docker: Listen on all interfaces

### ISSUE THREAD

**Issue by djarbz** [varun-raj/immich-power-tools#83]
I run all of my containers behind a reverse proxy on the host, so there is no port mapped outside of the container network.
As such, I have a `proxy` network and an `immich` network.

This container picks the `immich` network to listen on port `3000` instead of all networks and, as such, my reverse proxy cannot access it.

```bash
$ hostname -i
172.16.15.4 172.16.14.25
$ hostname
d91ff275f18f
```

```bash
docker logs -f immich_power_tools
  ▲ Next.js 14.2.5
  - Local:        http://d91ff275f18f:3000
  - Network:      http://172.16.15.4:3000

 ✓ Starting...
 ✓ Ready in 384ms
```

**Comment by djarbz** [comment]
It is working if I modify the `startServer` function as such:
```javascript
startServer({
  dir,
  isDev: false,
  config: nextConfig,
  hostname: '0.0.0.0',
  port: currentPort,
  allowRetry: false,
  keepAliveTimeout,
}).catch((err) => {
  console.error(err);
  process.exit(1);
});
```

While running in a container, we do not want the hostname set on this line and just want the ANY address. I don't know if there is a use-case if running outside of a container?
```
const hostname = process.env.HOSTNAME || '0.0.0.0'
```

**Comment by dperezq** [comment]
It's happening the same to me. I am not able to run it but no errors are shown in the logs. The browser returns me "ERR_CONNECTION_REFUSED" and no logs in the console, so I have no idea how to continue.

**Comment by djarbz** [comment]
@dperezq YOU can't, unless you rewrite the server.js to listen on all interfaces and mount that in to override the one that is included.

**Comment by BoiDLi** [comment]
I'm encountering the same problem. Can you explain how to override the server.js file?

**Comment by djarbz** [comment]
This is a section from my Docker Compose:
```yaml
  power-tools:
    container_name: immich_power_tools
    environment:
      DB_DATABASE_NAME: immich
      DB_HOST: database
      DB_PASSWORD: <REDACTED>
      DB_PORT: 5432
      DB_USERNAME: postgres
      EXTERNAL_IMMICH_URL: <REDACTED>
      GEMINI_API_KEY: <REDACTED>
      IMMICH_API_KEY: <REDACTED>
      IMMICH_URL: http://immich-server:2283
      TZ: America/Chicago
    image: ghcr.io/varun-raj/immich-power-tools:latest
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    networks:
      - ix-traefik_backend
      - stack
    ports:
      - host_ip: 100.100.1.5
        name: web-ui
        protocol: tcp
        published: 8007
        target: 3000
    restart: unless-stopped
    tmpfs:
      - /tmp
    volumes:
      - source: /mnt/apps/config/immich_power_tools_server.js
        target: /app/server.js
        type: bind
```

You'll see how I am mounting the modified server.js from the host FS to the container.
